### ISSUE TITLE
Jaeger with MongoDB setup

### ISSUE THREAD

**Issue by sandeepnalla1** [code-tool/jaeger-mongodb-collector#1]
Hi, I am new to this environment and i am trying to setup Jaegerui and push traces from MongoDB and this seems to be related.
Can I know steps on where to install a collector and how to send traces to JaegerUI..?

Thanks in advance.!

**Comment by allflame** [comment]
@sandeepnalla1 sorry for the late reply. This will only push traces for the ext-mongodb extension. You can consult https://github.com/code-tool/jaeger-mongodb-symfony-bridge on how to do it Symfony, but it's not required to use that particular framework
